language: ruby

before_install:
  - gem install bundler

before_script:
  - sudo su postgres -c "psql -c \"CREATE ROLE root SUPERUSER LOGIN PASSWORD 'oAutH2Prov'\" "
  - sudo su postgres -c "createdb -E UTF8 -T template0 --locale=en_US.utf8 -O root oauth2_test"
